"""Writes .md files to the Obsidian vault with correct wikilinks and structure."""

import re
from pathlib import Path

import frontmatter
from rich.console import Console

console = Console()


MAX_FILENAME_LEN = 100


def safe_name(name: str) -> str:
    """Strip characters that are invalid in file/folder names.

    Preserves spaces. Truncates to MAX_FILENAME_LEN to avoid
    hitting Windows 260-char path limits.
    """
    cleaned = re.sub(r'[/\\:?*"<>|]', "", name)
    if len(cleaned) > MAX_FILENAME_LEN:
        cleaned = cleaned[:MAX_FILENAME_LEN].rstrip()
    return cleaned


def write_hub_note(
    vault_root: Path,
    file_path: Path,
    title: str,
    children: list[str],
    children_heading: str,
    overwrite: bool = False,
) -> bool:
    """Write a hub note (subject, chapter, or topic level).

    Hub notes contain only links — no content, no descriptions.

    Args:
        vault_root: Root path of the Obsidian vault.
        file_path: Absolute path where the .md file should be written.
        title: Note title.
        children: List of child titles to link to.
        children_heading: Heading for the children section (e.g. "Chapters").
        overwrite: Whether to overwrite existing files.

    Returns:
        True if file was written, False if skipped.
    """
    if file_path.exists() and not overwrite:
        console.log(f"[dim]Skipping (exists): {file_path.relative_to(vault_root)}[/dim]")
        return False

    links = "\n".join(f"- [[{child}]]" for child in children)
    content = f"# {title}\n\n## {children_heading}\n{links}\n"

    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding="utf-8")
    console.log(f"[green]Written: {file_path.relative_to(vault_root)}[/green]")
    return True


def write_leaf_note(
    vault_root: Path,
    file_path: Path,
    note_content: str,
    needs_review: bool = False,
    overwrite: bool = False,
) -> bool:
    """Write a leaf (subtopic) note to the vault.

    If needs_review is True, a REVIEW flag is added to the YAML frontmatter.

    Args:
        vault_root: Root path of the Obsidian vault.
        file_path: Absolute path where the .md file should be written.
        note_content: The full markdown content generated by notes.py.
        needs_review: Whether the verification pass failed.
        overwrite: Whether to overwrite existing files.

    Returns:
        True if file was written, False if skipped.
    """
    if file_path.exists() and not overwrite:
        console.log(f"[dim]Skipping (exists): {file_path.relative_to(vault_root)}[/dim]")
        return False

    if needs_review:
        # Prepend YAML frontmatter with review flag
        post = frontmatter.Post(note_content)
        post["review"] = True
        post["review_reason"] = "Verification pass failed — spec coverage may be incomplete"
        output = frontmatter.dumps(post)
    else:
        output = note_content

    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(output, encoding="utf-8")

    status = "[red]Written (REVIEW): " if needs_review else "[green]Written: "
    console.log(f"{status}{file_path.relative_to(vault_root)}[/]")
    return True


def build_vault_paths(
    vault_root: Path,
    subject: str,
    chapter: str,
    topic: str,
    subtopic: str,
) -> dict[str, Path]:
    """Build all file paths for a given subtopic and its parent hubs.

    Returns:
        Dict with keys: subject_hub, chapter_dir, chapter_hub,
        topic_dir, topic_hub, leaf.
    """
    s = safe_name(subject)
    c = safe_name(chapter)
    t = safe_name(topic)
    st = safe_name(subtopic)

    subject_dir = vault_root / s
    chapter_dir = subject_dir / c
    topic_dir = chapter_dir / t

    return {
        "subject_hub": subject_dir / f"{s}.md",
        "chapter_dir": chapter_dir,
        "chapter_hub": chapter_dir / f"{c}.md",
        "topic_dir": topic_dir,
        "topic_hub": topic_dir / f"{t}.md",
        "leaf": topic_dir / f"{st}.md",
    }
